### ISSUE TITLE
MTP and ADB still not working on latest UBPorts build

### ISSUE THREAD

**Issue by KJS1212** [Kethen/samsung-exynos8890#10] opened 2023-08-02 16:34 UTC
I have enabled developer options and rebooted and adb still does not work. Running sudo adbd also doesn't work. MTP does not work and I have looked through every setting and booted my laptop into 2 linux distros and windows and still, MTP does not work. Please help

**Comment by Kethen** [comment] 2023-08-06 07:43
duplicate of https://gitlab.com/ubports/porting/community-ports/android11/samsung-galaxy-s7/samsung-exynos8890/-/issues/12

**Closed as completed by Kethen** 2023-08-06 07:43 UTC
